### ISSUE TITLE
Talk Proposal: A Partial Taxonomy Of Test Unreliability

### ISSUE THREAD

**Issue by Trott** [berlinjs/jsconf2019-special#10]
A Partial Taxonomy of Test Unreliability

Ah, those vexing tests that fail once in a while but pass as soon as you re-run them. Don’t you hate those things? I hate those things. And Node.js core used to have quite a problem with them. Will a fast-paced run-through of causes that are then placed into a maybe-possibly helpful taxonomy be useful? I don’t know! Maybe we’ll find out! Together! Like a team! Go team!

We’ll cover all your favorite classics like race conditions, deadlocks, side effects, you name it! We’ll also include b-sides and deep cuts that we had to invent names for, names that usually end up sounding like basketball teams. And we’ll talk about tools and techniques for reproducing and debugging these often-hard-to-reproduce-and-debug problems in tests. This talk is not to be missed, but that’s primarily because BerlinJS presumably only has one talk going at any given time, so what else would you be doing?

Talk duration: 20 minutes-ish

**Comment by carolstran** [comment]
Hey @Trott, thanks for submitting! 🙌 We have you down. We'll be looking over all the proposals in the next couple of days, so you should hear back from us, either way, later this week 🍰

**Comment by rmehner** [comment]
Hey @Trott,

very good proposal, touches a lot of annoyances people have with testing. We received way more proposals than we have slots to fill and your talk unfortunately didn't quite make it (choosing talks is super f***king hard). However, we have some 10 minute talk slots to fill and we'll have another round of voting on those asap. Would you be able to give a 10 minute version of that talk?

**Comment by Trott** [comment]
> Would you be able to give a 10 minute version of that talk?

Yes, I can do that!

**Comment by carolstran** [comment]
Great thank you @Trott! We'll be doing the second round of voting asap and we will let you know within the next couple of days 😁

**Comment by rmehner** [comment]
@Trott results are in and your talk didn't make it by a very, very small margin. Sorry :/ It's sure a really great talk and I hope you'll have the opportunity to give it somewhere and obviously still hope to meet you at our meetup!

if you're ever in Berlin, please hit us up and we're very happy to give you a spot at our regular meetup.

**Comment by carolstran** [comment]
Closing this issue now, but thanks again for submitting @Trott 💟 Like Robin mentioned, if you're ever in Berlin we'd love to have you!
