### ISSUE TITLE
Talk Proposal: You Don't Know Your Dependencies

### ISSUE THREAD

**Issue by a0viedo** [berlinjs/jsconf2019-special#11]
If you’re building applications chances are your dependency tree is in the order of hundreds. That can easily scale up to at least a thousand for large applications (like popular OS projects Ghost or Keystone). 
Join me in my hindered journey to address a big elephant in the room: managing dependencies. Updating a dependency or following common practices shouldn’t have to be a mysterious thing.
What’s the right thing to do in your package.json? Exact versions? Using a caret? What’s the reason behind lockfiles? What type of tooling is out there? I’ll present answers from my research to these common questions.

Talk duration: 25 minutes
Edit: talk duration 10 minutes

**Comment by carolstran** [comment]
Hey @a0viedo! Thanks for submitting, we have you down 💃 We're going to look over the proposals in the next couple of days, so you should hear from us either way later this week 🍭

**Comment by rmehner** [comment]
👋 @a0viedo 

As someone who worked on a certain project that takes care of updating dependencies, I've seen a lot of misconceptions around dependency management that people have and this talk sure is important :) 

However, we only have three main talk slots to fill and received way more proposals than that. Your talk didn't quite make it (and please don't attribute this to the quality, it's excellent, just hard to pick talks from that many proposals :)). We do have some 10 minute talk slots to fill and will have a second round of voting on those asap. Would you be able to give a 10 minute version of that talk?

**Comment by a0viedo** [comment]
@rmehner thanks for the swift response! Sure, I can squash a few things to fit it into 10min slot. Let me know if you need anything else.

**Comment by JuanCaicedo** [comment]
@a0viedo Looking forward to hearing your talk!! 😄🙌

**Comment by carolstran** [comment]
Great thank you @a0viedo! We'll be doing the second round of voting asap and we will let you know within the next couple of days 😁

**Comment by rmehner** [comment]
@a0viedo Vote's over and your talk has made it :) 10 minutes it is! :)

**Comment by carolstran** [comment]
Hey @a0viedo, can you confirm that you got this? We've also added you to the website and will announce asap 🎉 https://jsconf.berlinjs.org/

**Comment by a0viedo** [comment]
thanks @carolstran @rmehner! I'll be there

**Comment by carolstran** [comment]
Yay thanks!

**Comment by a0viedo** [comment]
thanks everyone! it was to meet you

**Comment by rmehner** [comment]
@a0viedo thanks again for your talk, I forwarded some quotes of it to my friends over at Greenkeeper :)

If you're ever in Berlin again, give us a shout!
