### ISSUE TITLE
Talk Proposal: Johnny-Five and the Rise of JavaScript Hardware

### ISSUE THREAD

**Issue by nebrius** [berlinjs/jsconf2019-special#7]
## Abstract

Johnny-Five was created 6 years ago and in the process kickstarted the JavaScript robotics movement and JavaScript based IoT. J5, as we call it, has been around ever since the rise of modern IoT, and the project has a lot to teach us.

JavaScript and J5 brings a lot to the table for hardware. The asynchronous nature of JavaScript fits perfectly with real-world sensors, and the digital UI origins of JavaScript dovetail nicely with the physical UI of hardware. Most importantly, we focused the project on non-experts and we cultivated a welcoming, inclusive community.

Knowing these lessons and more are critical going forward if we hope to create open and ethical IoT ecosystem.

## Details

This talk will have the following outline:

- Why JavaScript for Hardware?
- Overview of using Johnny-Five
- The importance of OSS and Community

## Previous Recording

https://www.youtube.com/watch?v=tJV-qb8a4y8

**Comment by carolstran** [comment]
@nebrius Same with this one 😇

**Comment by carolstran** [comment]
@nebrius I fought hard for this one 🤖- but I was overruled 😩 So closing for now, but please see my post on your other submission!

**Comment by nebrius** [comment]
So it goes. I prefer this talk too, but I also know my other talk is really useful for attendees.

**Comment by rmehner** [comment]
@nebrius haha, absolutely no doubt that this one is great and useful (I've played tons with Johnny Five and have run NodeCopter in the past), we just thought the other one fits a bit better in the whole scheme of talks we'll have that night :)
