### ISSUE TITLE
Talk Proposal: Are GraphQL and Microservices Good Friends?

### ISSUE THREAD

**Issue by RamirezAlex** [berlinjs/jsconf2019-special#8]
## Abstract
Having several microservices exposing their APIs through an API Gateway isn't uncommon, and it is also expected that we require communication between those microservices. I am currently working on a project with some microservices in Node.js where the communication between them and the clients was kind of a mess. 

In this talk, I am going to show you some different options I have explored in order to address this communication; how we improved it with GraphQL and the outcomes of it. By the end of the talk, you will find out if GraphQL and Microservices are Good Friends.

## About me
* Software Developer & Blockchain Padawan.
* JavaScript Lover and co-organizer of MedellinJS (Medellin, Colombia)
https://twitter.com/RamirezAlex_

### Previous Talks
I have spoken before in meetups, but not in International Conferences, so I have not video recordings of it. This talk would be my second one in English, which is not my mother tongue.

### Talk time
15-20 Minutes

**Comment by carolstran** [comment]
Hey @RamirezAlex, thanks for submitting! We have your proposal down ☑️ We're looking over the proposals in the next couple of days, so we'll let you know either way later this week 😁

**Comment by rmehner** [comment]
👋

Great work with MedellinJS over there, hearing good things about it ❤️ 

As for your talk: We received way more proposals than we have slots and your talk didn't quite make it (it's always hard to choose, as you might now). However, we have some 10 minute slots to fill and for those we'll have a second round of voting asap.

Would you be able to give that talk in 10 minutes?

**Comment by RamirezAlex** [comment]
Hi @rmehner and @carolstran 

Thank you for the good words about MedellinJS and for reviewing my talk proposal. I can absolutely give it in 10 minutes, and I was actually kind of expecting that I needed to skip some demos and cut down some slides to keep in that timeframe. Which I already did 😊

**Comment by carolstran** [comment]
Great thank you @RamirezAlex! We'll be doing the second round of voting asap and we will let you know within the next couple of days 😁

**Comment by rmehner** [comment]
@RamirezAlex second vote is done and results are in. Unfortunately we can't give you a spot this time (wish we would have more time), but we sure hope you'll have the opportunity to give your talk somewhere :)

If you're ever in Berlin, please hit us up, we would be very happy to give you a spot at our regular meetup.

**Comment by RamirezAlex** [comment]
Thank you @rmehner :)

**Comment by carolstran** [comment]
Closing this issue now, but thanks again for submitting @RamirezAlex 💟 Like Robin mentioned, if you're ever in Berlin we'd love to have you!
